# Generated by Django 5.1.7 on 2026-08-04 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("paystack", "Paystack"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("carte", "Carte bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("MTN_money", "MTN Money"),
                            ("MOOV_money", "MOOV Money"),
                            ("WAVE_money", "WAVE Money"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("reussi", "Réussi"),
                            ("echoue", "Échoué"),
                            ("rembourse", "Remboursé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("ip_client", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("paye_le", models.DateTimeField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="tickets.commande",
                    ),
                ),
            ],
        ),
    ]
