# Generated by Django 5.1.7 on 2026-08-04 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("payment", "Paiement"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("modele", models.CharField(max_length=100)),
                ("objet_id", models.CharField(max_length=100)),
                ("ancienne_valeur", models.JSONField(blank=True, null=True)),
                ("nouvelle_valeur", models.JSONField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_securite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="SessionUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("adresse_ip", models.GenericIPAddressField()),
                ("pays", models.CharField(blank=True, max_length=100)),
                ("appareil", models.CharField(blank=True, max_length=150)),
                ("navigateur", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("derniere_activite", models.DateTimeField(auto_now=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_securite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
