# Generated by Django 5.1.7 on 2026-08-04 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodePromotionnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "type_reduction",
                    models.CharField(
                        choices=[
                            ("pourcentage", "Pourcentage"),
                            ("montant", "Montant fixe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reduction", models.DecimalField(decimal_places=2, max_digits=5)),
                ("utilisation_max", models.PositiveIntegerField(default=1)),
                ("expire_le", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section", models.CharField(max_length=50)),
                ("rangee", models.CharField(max_length=10)),
                ("numero", models.CharField(max_length=10)),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="events.lieu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeBillet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite_initiale", models.PositiveIntegerField(default=0)),
                ("quantite_vendue", models.PositiveIntegerField(default=0)),
                ("place_assignee", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types_billets",
                        to="events.evenement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                ("token_qr", models.CharField(max_length=255, unique=True)),
                ("scanne", models.BooleanField(default=False)),
                ("date_scan", models.DateTimeField(blank=True, null=True)),
                ("statut", models.CharField(default="valide", max_length=20)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billets",
                        to="tickets.commande",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billets",
                        to="tickets.place",
                    ),
                ),
                (
                    "type_billet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billets",
                        to="tickets.typebillet",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("lieu", "section", "rangee", "numero"), name="unique_place_lieu"
            ),
        ),
    ]
